### ISSUE TITLE
Tensorflow implementation

### ISSUE THREAD

**Issue by SHAOLLL** [phanideepgampa/stacked-capsule-networks#1]
Do you have a Tensorflow implementation of the Stacked Capsule Autoencoder (SCAE)?

**Comment by phanideepgampa** [comment]
Thanks for stopping by!! Unfortunately, I have implemented it only in PyTorch :).

Here is the link for the official repository of the authors. It is implemented in TensorFlow. [https://github.com/google-research/google-research/tree/master/stacked_capsule_autoencoders](url)
