### ISSUE TITLE
No grad for templets and x_m in pcae

### ISSUE THREAD

**Issue by Harry-Up** [phanideepgampa/stacked-capsule-networks#3]
There is no grad for templets and x_m since the transform_templet is obtained by PIL func. In that case, the variables are transformed to PIL image instances and then, back to tensors. Therefore, the grad_fn is lost during the processing. 

Writing an affine func in pytorch may help. (also boost the efficiency).

**Comment by phanideepgampa** [comment]
Hey @Harry-Up, thank you for pointing out the issue. Maybe this was the reason I was not able to reproduce the exact results. Yeah, your idea of affine function seems the best way to tackle the issue. 
Maybe you could raise a pull-request if you have implemented it, this would also help others including me :).

**Comment by Harry-Up** [comment]
Thanks for your reply :). 

Yeah, we could apply F.affine_grid and F.grid_sample in torch.nn.functional to do it. 

However, I am confused another thing that the pose values are constrained by ReLU in the range of (-∞, ∞). In practice, we need an angle param in [-180°, 180°], a translate param in [-1.0, 1.0], a scale param in (0, ∞) and a shear param in [-180°, 180°]. Maybe, a further activation is needed.

**Comment by phanideepgampa** [comment]
Thanks for your pull-request !!
