### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by Ahme1994** [phanideepgampa/stacked-capsule-networks#8]
hello sir when i am running your code i got this error 
TypeError                                 Traceback (most recent call last)
<ipython-input-16-7f45cb4285df> in <module>
    213 if __name__ == "__main__":
    214     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
--> 215     pcae = PCAE()
    216     temp = torch.randn(5,1,28,28).to(device)
    217     pcae.to(device)

TypeError: __init__() missing 1 required positional argument: 'config'

**Comment by caodapeng0101** [comment]
Excuse me,
The same upper questions, could you please give us some way to fix them, thank you。

**Comment by phanideepgampa** [comment]
I think you are running "model.py"  file, that code was written for debugging purposes, you can find the code in main.py for passing config and other arguments. :)
